### ISSUE TITLE
Program doesnt find certain user-defined seeds

### ISSUE THREAD

**Issue by MiranCZ** [19MisterX98/Nether_Bedrock_Cracker#20]
The program doesn't seem to find some seeds....
For example, if you use data from the seed `-9098865772979074265` the program only finds the followings ones:
`-3190143061868983513`, `2749823371655990055`, `9094800062677759692`, `-3411977577506818356`

I am not 100% sure about this, but what I think is happening is that the nether only uses the bottom 48 bits of the seed to generate...
So every nether has 2^16 (65,536) different overworlds that lead to it. 
You can check that if you compare two of the found seeds with the one I entered, they indeed have same 48 or more lower bits.

`-9098865772979074265` = 1000000110111010**010101011100100110001110100111110100101100100111**
`-3190143061868983513` = 1101001110111010**010101011100100110001110100111110100101100100111**
`2749823371655990055` ..= 0010011000101001**010101011100100110001110100111110100101100100111**

the fact the program only found two of those 65 thousand-ish seeds means, it probably doesn't work for most nether seeds...
(it finds a seed that has the same nether as the entered one, but the overworld is different)

**Comment by 19MisterX98** [comment]
Yes, this is intentional. Bedrock only uses the lower 48 bits and spitting out thousands of results for every matching base seed is probably not the best of ideas. 
The program has a drop-down where the user can choose between structure seed and world seed mode. Structure seed mode outputs the base seed. World seed mode outputs the world seeds that can be randomly generated for that structure seed. The rng that creates world seeds can only generate 2^48 of all 2^64 seeds so the amount of randomly generated world seeds that match a structure seed is 1:1. It can happen of course that no or two world seeds match a structure seed.

Some additional filtering needs to happen for user specified seeds. Filtering based on the structure seed and biomes with cubiomes should work for example.

**Comment by MiranCZ** [comment]
> The rng that creates world seeds can only generate 2^48 of all 2^64 seeds

Ohh, I see it uses `Random.create().nextLong()` when the seed is left blank (right?). So if you don't input a seed there are only 2^48 possible worlds that can generate instead of the 2^64?

**Comment by 19MisterX98** [comment]
Yep

**Comment by MiranCZ** [comment]
Ah, makes sense! Thanks for the explanation...
